version: 2
jobs:
  build:
    docker: # run the seps with Docker
      - image: rawdee/sfdx:latest
    steps: # steps that comprise the `build` job
      - checkout # checkout the source code to working directory
      - run: 
          name: "echo my current working directory"
          command: pwd
      - run:
          name: "store server key file"
          command: echo ${jwt} > $PWD/jwt.key
      - run:
          name: "working branch"
          # Alternatively, you can run the environment variable without curly brances;
          command: echo ${CIRCLE_BRANCH}
      - run:
          name: "custom environment variable: env"
          command: echo ${ENV}
      - run: 
          name: "sfdx version"
          command: sfdx --version
      - run:
          name: "authorize to org"
          command: sfdx force:auth:jwt:grant --clientid ${client_id} --jwtkeyfile $PWD/jwt.key --username ${username} 

workflows:
  version: 2
  sfdx-cicd:
    jobs:
      - build